global:
  scrape_interval: 3s

scrape_configs:
- job_name: mongo
  static_configs:
  - targets: ['mongo-exporter:9216']
- job_name: node
  static_configs:
    - targets: ['node-exporter:9100']
- job_name: sample-service
  static_configs:
    - targets: ['web:3000']